#ifndef _FEATURES_H_
#define /* _FEATURES_H_ */

#define CPUID_FEAT_ECX_SSE3		0
#define CPUID_FEAT_ECX_PCLMULQDQ	1
#define CPUID_FEAT_ECX_DTES64		2
#define CPUID_FEAT_ECX_MONITOR		3
#define CPUID_FEAT_ECX_DS_CPL		4
#define CPUID_FEAT_ECX_VMX		5
#define CPUID_FEAT_ECX_SMX		6
#define CPUID_FEAT_ECX_EIST		7
#define CPUID_FEAT_ECX_TM2		8
#define CPUID_FEAT_ECX_SSSE3		9
#define CPUID_FEAT_ECX_CNTX_ID		10
#define CPUID_FEAT_ECX_SDBG		11
#define CPUID_FEAT_ECX_FMA		12
#define CPUID_FEAT_ECX_CMPXCHG16B	13
#define CPUID_FEAT_ECX_TPR_UPD		14
#define CPUID_FEAT_ECX_PDCM		15
#define CPUID_FEAT_ECX_SSE4_1		19
#define CPUID_FEAT_ECX_SSE4_2		20
#define CPUID_FEAT_ECX_X2APIC		21
#define CPUID_FEAT_ECX_MOVBE		22
#define CPUID_FEAT_ECX_POPCNT		23
#define CPUID_FEAT_ECX_AESNI		25
#define CPUID_FEAT_ECX_XSAVE		26
#define CPUID_FEAT_ECX_OSXSAVE		27
#define CPUID_FEAT_ECX_AVX		28
#define CPUID_FEAT_ECX_F16C		29
#define CPUID_FEAT_ECX_RDRAND		30
 
#define CPUID_FEAT_EDX_FPU		0
#define CPUID_FEAT_EDX_VME		1
#define CPUID_FEAT_EDX_DE		2
#define CPUID_FEAT_EDX_PSE		3
#define CPUID_FEAT_EDX_TSC		4
#define CPUID_FEAT_EDX_MSR		5
#define CPUID_FEAT_EDX_PAE		6
#define CPUID_FEAT_EDX_MCE		7
#define CPUID_FEAT_EDX_CX8		8
#define CPUID_FEAT_EDX_APIC		9
#define CPUID_FEAT_EDX_SEP		11
#define CPUID_FEAT_EDX_MTRR		12
#define CPUID_FEAT_EDX_PGE		13
#define CPUID_FEAT_EDX_MCA		14
#define CPUID_FEAT_EDX_CMOV		15
#define CPUID_FEAT_EDX_PAT		16
#define CPUID_FEAT_EDX_PSE36		17
#define CPUID_FEAT_EDX_PSN		18
#define CPUID_FEAT_EDX_CLFSH		19
#define CPUID_FEAT_EDX_DS		21
#define CPUID_FEAT_EDX_ACPI		22
#define CPUID_FEAT_EDX_MMX		23
#define CPUID_FEAT_EDX_FXSR		24
#define CPUID_FEAT_EDX_SSE		25
#define CPUID_FEAT_EDX_SSE2		26
#define CPUID_FEAT_EDX_SS		27
#define CPUID_FEAT_EDX_HTT		28
#define CPUID_FEAT_EDX_TM		29
#define CPUID_FEAT_EDX_PBE		31

#endif /* _FEATURES_H_ */
